name: Build executable

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.1
      with:
        version: 12.16.0
    - name: Install dependencies
      run: yarn
    - name: Transpile source code
      run: yarn transpile
    - name: Build into single-file script
      run: yarn rollup
    - name: Pack into executable
      run: yarn package
